### ISSUE TITLE
PHP 7.4.30 错误: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by AlanYe-Dev** [Ancgk-Studio/RssQTsend#5]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/45558679/182021854-ca0856e3-ef67-4925-8fff-3314c8cb2c91.png">
经检验配置文件不存在问题，报错代码位于此处
<img width="611" alt="image" src="https://user-images.githubusercontent.com/45558679/182021884-30fa60a5-a1ae-456c-a405-f3f75bb26a34.png">

**Comment by cdwcgt** [comment]
如果可能的话，是否可以上传一份删除了敏感信息的配置文件
我这边测试一下

**Comment by AlanYe-Dev** [comment]
[config.zip](https://github.com/Ancgk-Studio/RssQTsend/files/9229937/config.zip)

**Comment by AlanYe-Dev** [comment]
我是使用 [go-cqhttp](https://github.com/Mrs4s/go-cqhttp/) 作为机器人框架的，框架那边也能够正常登录

**Comment by cdwcgt** [comment]
```
//"proxyServer": "127.0.0.1:1080",
```
请直接留空
json是不支持注释的

**Comment by AlanYe-Dev** [comment]
<img width="975" alt="image" src="https://user-images.githubusercontent.com/45558679/182076753-a220e4a5-100f-44f0-a2e3-f336d9837e68.png">
这是现在的一个配置

**Comment by AlanYe-Dev** [comment]
<img width="504" alt="image" src="https://user-images.githubusercontent.com/45558679/182077127-862cede6-5385-4b8b-a4f0-cac7f6ca65b1.png">
[修改后.zip](https://github.com/Ancgk-Studio/RssQTsend/files/9231094/default.zip)
config.json是RssQTsend的配置文件，config-edited.yml 是 go-cqhttp 的配置文件

**Comment by cdwcgt** [comment]
28,39,50,61后面的]应该去掉
[]内的是集合
请使用 json 实用工具验证自己的 json 格式
json.cn
https://c.runoob.com/front-end/53/

**Comment by AlanYe-Dev** [comment]
其实是27行最后的","导致的错误
现在程序运作一切正常，万分感谢，很抱歉打扰您了 (笑哭
