### ISSUE TITLE
无法下载 Twitter 图片附件

### ISSUE THREAD

**Issue by AlanYe-Dev** [Ancgk-Studio/RssQTsend#6]
<img width="837" alt="image" src="https://user-images.githubusercontent.com/45558679/182103007-1d902dec-7dc4-4cb1-a6ab-a26c5db4095d.png">
经测试，在香港服务器上不使用代理时也无法下载 Twitter 图片

**Comment by skilittle** [comment]
方便提供一下RSS链接吗？

**Comment by AlanYe-Dev** [comment]
https://rsshub.app/twitter/user/sonic_hedgehog

**Comment by AlanYe-Dev** [comment]
![5F_(WXL0$1J`_ S{WC%`I6I](https://user-images.githubusercontent.com/45558679/182106014-3af6ce0d-2334-43d0-9faa-25ff8c126568.png)
我猜测是这里出现的问题

**Comment by AlanYe-Dev** [comment]
RSSHub 给出的图片链接是: https://pbs.twimg.com/media/FYtcGSuUEAA_isv?format=jpg&amp;name=orig
该链接无法直接打开，但是将"?format=jpg&amp;name=orig" 改为 ".jpg" 时便可访问
例如: https://pbs.twimg.com/media/FYtcGSuUEAA_isv.jpg

**Comment by skilittle** [comment]
![image](https://user-images.githubusercontent.com/53262738/182108325-764c6c91-6f52-49e2-90eb-c448f7312d82.png)
![image](https://user-images.githubusercontent.com/53262738/182108552-895c330c-964f-4aaa-bf60-b85426fa772c.png)
![image](https://user-images.githubusercontent.com/53262738/182109016-63c50c6e-4123-4bfa-a0c7-a96238bc3a76.png)
![image](https://user-images.githubusercontent.com/53262738/182108848-27c716a2-0551-43ca-b9a0-be99bd7d3c0f.png)
RSSHub在返回的链接中夹带了一个本不应该存在的空格，但这种情况似乎只发生在部分推文。

**Comment by AlanYe-Dev** [comment]
嗯... 个人感觉并不是空格的问题，而是 RSSHub 把 "&" 转换为其HTML的转义字符 "&amp;" 了
https://blog.csdn.net/qq_26296197/article/details/78470481

**Comment by AlanYe-Dev** [comment]
一般浏览器会自动把该转义字符转换为 "&" (URL除外)，或许直接将<img width="37" alt="image" src="https://user-images.githubusercontent.com/45558679/182111195-da004fc6-730d-44c6-9e59-008dbb967776.png">转换为 "&" 即可解决

**Comment by skilittle** [comment]
我指的正是这个转义符，过后我会进一步修正此问题
